events {}

http {

  server {
    listen 80;
    server_name localhost;

    location ^~ /us-en {
        rewrite ^/us-en(/.*)$ $1 break;
        proxy_pass http://wordpress_apache:80;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header CF-IPCountry US;
        proxy_set_header X-Forwarded-Prefix /us-en;
        proxy_set_header X-Original-URI $request_uri;
        proxy_redirect off;
    }

  }

}
