services:

  # 本地已经有 docker-compose + nginx + wordpress + mysql，
  # 要模拟 CDN 按路径回源（path based origin routing），本质就是让 nginx 充当“本地 CDN”
  # 
  # 所以我们要配置 nginx.conf，让 nginx 充当“本地 CDN”
  # 这样我们就可以实现 CDN 按路径回源，比如 /us-en/ 访问 wordpress
  # 
  cdn:
    image: nginx:1.27
    ports:
      - "80:80"
    depends_on:
      - wordpress_apache
      - wordpress_frankenphp
    volumes:
      - .docker/cdn/nginx.conf:/etc/nginx/nginx.conf

  wordpress_apache:
    image: yao3060/wordpress:php8.4-apache
    restart: "no"
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-wordpress_apache_db}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-root}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-domain}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_POST_REVISIONS', 3 );
        define( 'WP_SITEURL', 'http://localhost/us-en' );
        define( 'WP_HOME', 'http://localhost/us-en' );
    command: ["apache2-foreground"]
    volumes:
      - ./src:/var/www/html:delegated
      - .docker/php/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
      - .docker/php/wp.ini:/usr/local/etc/php/conf.d/wp.ini
    depends_on:
      wordpress_apache_db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M

  wordpress_apache_db:
    image: mysql:8.0
    restart: "no"
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-domain}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD:-root}
    volumes:
      - wordpress_apache_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s


  wordpress_frankenphp:
    image: yao3060/wordpress:php8.4-frankenphp
    restart: "no"
    ports:
      - "${WORDPRESS_HTTP_PORT:-8000}:8000"
    environment:
      SERVER_NAME: ${SERVER_NAME:-:8000}
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST:-wordpress_frankenphp_db}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-root}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-root}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-domain}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-0}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_POST_REVISIONS', 3 );
        define( 'WP_SITEURL', 'http://localhost/eu-en' );
        define( 'WP_HOME', 'http://localhost/eu-en' );
    volumes:
      - ./src:/var/www/html:delegated
      - ./wordpress-php-8.4-frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - .docker/php/opcache-recommended.ini:/usr/local/etc/php/conf.d/opcache-recommended.ini
      - .docker/php/wp.ini:/usr/local/etc/php/conf.d/wp.ini
      - caddy-data:/data
      - caddy-config:/config
    command: ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]
    depends_on:
      wordpress_frankenphp_db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 256M

  wordpress_frankenphp_db:
    image: mysql:8.0
    restart: "no"
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-domain}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD:-root}
    volumes:
      - wordpress_frankenphp_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  adminer:
    image: adminer
    restart: "no"
    environment:
      - ADMINER_PLUGINS=tables-filter tinymce
      # - ADMINER_DEFAULT_SERVER=wordpress_apache_db
      # - ADMINER_DESIGN='nette'
    ports:
      - 8081:8080

volumes:
  wordpress_apache_db_data:
  wordpress_frankenphp_db_data:
  caddy-data:
  caddy-config:
